### ISSUE TITLE
Theme is broken (page.extra.author).

### ISSUE THREAD

**Issue by ghost** [rust-br/dinkleberg#6]
Serving the zola blog using this theme version is impossible due to a misplaced template tag in `page.html` file.

```
Reason: Failed to render 'dinkleberg/templates/page.html'
Reason: Variable `page.extra.author` not found in context while rendering 'dinkleberg/templates/page.html'
```

**Comment by drewdeponte** [comment]
@VentGrey that just means that you need to specify the author property under the `[extra]` section in the front-matter of the page.

**Comment by ghost** [comment]
Sadly that feature is not docummented in the main repo or in the zola main site :( , and adding the property in any-page (or even the .toml :sweat_smile:) doesn't trigger the build, in fact the error is the same:

```
Reason: Variable `page.extra.author` not found in context while rendering 'dinkleberg/templates/page.html'
```

(Wrong) - In the .toml file
![image](https://user-images.githubusercontent.com/24773698/53139395-202cb480-354f-11e9-9fcb-bdbab72ee4bc.png)

(Wrong?)  - In a normal `.md` file that should work as a page.
![image](https://user-images.githubusercontent.com/24773698/53139443-47838180-354f-11e9-9517-211ea9658f29.png)

Maybe I'm missing something or something just broke with the new zola versions(?).

I'll try some variants and report later, thanks for your response :)

**Comment by drewdeponte** [comment]
I am using zola 0.5.1 and it works fine for me. The way I figured it out was realizing that the theme actually includes a full blown zola site as an example in it.

Then I coppied over the blog post from the example into mine and that is how I realized what the theme was expecting in terms of front-matter.

**Comment by drewdeponte** [comment]
I agree it isn't documented extremely well. Maybe that is an area you could help contribute to.

**Comment by VictorAlmeidaFonseca** [comment]
I solved this issue putting the  "[extra] Author: xxxxx"  on file "content/my_new_post.md". You could look the  file on the path "themes/dinkleberg/content/hello-world.md" and use like a model for you new post
